# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # you may remove this if you don't need go generate
env:
  - GO111MODULE=on
builds:
- main: ./cmd/asteboids/main.go
  binary: asteboids
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^doc:'
    - '^tests:'
    - '^test:'
    - '^chore:'
    - '^refacto:'
