name: Test
on: [push, pull_request]
jobs:
#  golangci:
#    name: Golangci-lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#          version: v1.36
#          # Optional: golangci-lint command line arguments.
#          #args: -v
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.16']
    runs-on: ${{ matrix.os }}
    name: Run go tests on ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go version

    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Xvfb
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Test
      run: go test ./...